apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 288434312749.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:05c3c0ec2932f5505e7775dc06e590dd66cbc1a9
        ports:
        - containerPort: 80
