apiVersion: v1
kind: Service
metadata:
  name: earphones-frontend-service
  labels:
    app: earphones-frontend
spec:
  type: ClusterIP
  selector:
    app: earphones-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
