apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 288434312749.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:ac055a4774c525de609ed22afb10360c39497578
        ports:
        - containerPort: 80
