apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:6be932bbda38dd8aa41f2391be3f5f9e15513245
        ports:
        - containerPort: 80
