apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlepay:5b6ab7b8bad215742f037de578812185f5d1de98
        ports:
        - containerPort: 80
