apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlepay:6be932bbda38dd8aa41f2391be3f5f9e15513245
        ports:
        - containerPort: 80
