apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 288434312749.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-phones:05c3c0ec2932f5505e7775dc06e590dd66cbc1a9
        ports:
        - containerPort: 80
