apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 288434312749.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlegrocery:12285c4a5fcc57f30a13dba377b90ceb87cd35ea
        ports:
        - containerPort: 80
